### ISSUE TITLE
HTML site not working 

### ISSUE THREAD

**Issue by omnidotnet** [omnidotnet/hasher#1]
The simple HTML is broken. The last ```<h2>``` seems to be indented into the list (which I closed), the ```<title>``` tag doesn't work, and the CSS is just not doing anything.

**Comment by KaamadanStudios** [comment]
Update: 
- Issue fixed by @RhugwedaShedge
- HTML reformatted by him too
- Closing this issue.

**Comment by omnidotnet** [comment]
Update:
- Issue fixed by @RhugwedaShedge
- HTML reformatted by him in the issue-fixing process
- Issue hereby closed
